,dep,version,filepath,bloated,cve,affected versions,advisory
0,ovmsclient,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,no one,no one,no one
1,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2016-1517,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2016-1517: OpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks.
2,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-12602,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12602: OpenCV through 3.3 has a denial of service (memory consumption) issue, as demonstrated by the 10-opencv-dos-memory-exhaust test case."
3,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-12603,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12603: OpenCV through 3.3 has an invalid write in the cv::RLByteStream::getBytes function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 2-opencv-heapoverflow-fseek test case."
4,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-12597,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12597: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread.
5,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-12599,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12599: OpenCV through 3.3 has an out-of-bounds read error in the function icvCvt_BGRA2BGR_8u_C4C3R when reading an image file by using cv::imread.
6,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-12606,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12606: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow4 in utils.cpp when reading an image file by using cv::imread.
7,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-12601,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12601: OpenCV through 3.3 has a buffer overflow in the cv::BmpDecoder::readData function in modules/imgcodecs/src/grfmt_bmp.cpp when reading an image file by using cv::imread, as demonstrated by the 4-buf-overflow-readData-memcpy test case."
8,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-12604,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for  CVE-2017-12604: OpenCV through 3.3 has an out-of-bounds write error in the FillUniColor function in utils.cpp when reading an image file by using cv::imread.
9,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-12600,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12600: OpenCV through 3.3 has a denial of service (CPU consumption) issue, as demonstrated by the 11-opencv-dos-cpu-exhaust test case."
10,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-12598,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12598: OpenCV through 3.3 has an out-of-bounds read error in the cv::RBaseStream::readBlock function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 8-opencv-invalid-read-fread test case."
11,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
12,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
13,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
14,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
15,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2019-19624,<4.1.0.25,"Opencv-python 4.1.0.25 includes a fix for CVE-2019-19624: An out-of-bounds read was discovered in OpenCV before 4.1.1. Specifically, variable coarsest_scale is assumed to be greater than or equal to finest_scale within the calc()/ocl_calc() functions in dis_flow.cpp. However, this is not true when dealing with small images, leading to an out-of-bounds read of the heap-allocated arrays Ux and Uy."
16,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2019-9423,<4.1.1.26,"Opencv-python 4.1.1.26 includes a fix for CVE-2019-9423: In opencv calls that use libpng, there is a possible out of bounds write due to a missing bounds check. This could lead to local escalation of privilege with no additional execution privileges required. User interaction is not required for exploitation."
17,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2019-15939,<4.1.1.26,Opencv-python 4.1.1.26 includes a fix for CVE-2019-15939: An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.
18,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2019-16249,<4.1.2.30,Opencv-python 4.1.2.30 includes a fix for  CVE-2019-16249: OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.
19,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
20,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
21,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
22,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
23,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
24,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
25,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
26,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
27,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
28,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
29,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
30,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
31,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
32,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
33,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
34,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
35,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
36,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
37,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
38,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/image_classification_using_tf_model/python/requirements.txt,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
39,ovmsclient,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,no one,no one,no one
40,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2016-1517,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2016-1517: OpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks.
41,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-12602,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12602: OpenCV through 3.3 has a denial of service (memory consumption) issue, as demonstrated by the 10-opencv-dos-memory-exhaust test case."
42,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-12603,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12603: OpenCV through 3.3 has an invalid write in the cv::RLByteStream::getBytes function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 2-opencv-heapoverflow-fseek test case."
43,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-12597,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12597: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread.
44,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-12599,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12599: OpenCV through 3.3 has an out-of-bounds read error in the function icvCvt_BGRA2BGR_8u_C4C3R when reading an image file by using cv::imread.
45,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-12606,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12606: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow4 in utils.cpp when reading an image file by using cv::imread.
46,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-12601,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12601: OpenCV through 3.3 has a buffer overflow in the cv::BmpDecoder::readData function in modules/imgcodecs/src/grfmt_bmp.cpp when reading an image file by using cv::imread, as demonstrated by the 4-buf-overflow-readData-memcpy test case."
47,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-12604,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for  CVE-2017-12604: OpenCV through 3.3 has an out-of-bounds write error in the FillUniColor function in utils.cpp when reading an image file by using cv::imread.
48,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-12600,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12600: OpenCV through 3.3 has a denial of service (CPU consumption) issue, as demonstrated by the 11-opencv-dos-cpu-exhaust test case."
49,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-12598,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12598: OpenCV through 3.3 has an out-of-bounds read error in the cv::RBaseStream::readBlock function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 8-opencv-invalid-read-fread test case."
50,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
51,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
52,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
53,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
54,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2019-19624,<4.1.0.25,"Opencv-python 4.1.0.25 includes a fix for CVE-2019-19624: An out-of-bounds read was discovered in OpenCV before 4.1.1. Specifically, variable coarsest_scale is assumed to be greater than or equal to finest_scale within the calc()/ocl_calc() functions in dis_flow.cpp. However, this is not true when dealing with small images, leading to an out-of-bounds read of the heap-allocated arrays Ux and Uy."
55,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2019-9423,<4.1.1.26,"Opencv-python 4.1.1.26 includes a fix for CVE-2019-9423: In opencv calls that use libpng, there is a possible out of bounds write due to a missing bounds check. This could lead to local escalation of privilege with no additional execution privileges required. User interaction is not required for exploitation."
56,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2019-15939,<4.1.1.26,Opencv-python 4.1.1.26 includes a fix for CVE-2019-15939: An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.
57,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2019-16249,<4.1.2.30,Opencv-python 4.1.2.30 includes a fix for  CVE-2019-16249: OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.
58,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
59,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
60,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
61,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
62,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
63,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
64,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
65,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
66,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
67,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
68,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
69,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
70,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
71,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
72,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
73,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
74,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
75,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
76,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
77,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/face_blur/python/requirements.txt,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
78,validators,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/bert_question_answering/python/requirements.txt,False,CVE-2019-19588,">=0.12.2,<=0.12.5",The validators package 0.12.2 through 0.12.5 for Python enters an infinite loop when validators.domain is called with a crafted domain string. This is fixed in 0.12.6. See: CVE-2019-19588.
79,ovmsclient,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/bert_question_answering/python/requirements.txt,False,no one,no one,no one
80,kaldi-python-io,==1.2.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/speech_recognition_with_kaldi_model/python/requirements.txt,False,no one,no one,no one
81,ovmsclient,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,no one,no one,no one
82,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2016-1517,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2016-1517: OpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks.
83,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-12602,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12602: OpenCV through 3.3 has a denial of service (memory consumption) issue, as demonstrated by the 10-opencv-dos-memory-exhaust test case."
84,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-12603,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12603: OpenCV through 3.3 has an invalid write in the cv::RLByteStream::getBytes function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 2-opencv-heapoverflow-fseek test case."
85,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-12597,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12597: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread.
86,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-12599,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12599: OpenCV through 3.3 has an out-of-bounds read error in the function icvCvt_BGRA2BGR_8u_C4C3R when reading an image file by using cv::imread.
87,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-12606,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12606: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow4 in utils.cpp when reading an image file by using cv::imread.
88,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-12601,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12601: OpenCV through 3.3 has a buffer overflow in the cv::BmpDecoder::readData function in modules/imgcodecs/src/grfmt_bmp.cpp when reading an image file by using cv::imread, as demonstrated by the 4-buf-overflow-readData-memcpy test case."
89,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-12604,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for  CVE-2017-12604: OpenCV through 3.3 has an out-of-bounds write error in the FillUniColor function in utils.cpp when reading an image file by using cv::imread.
90,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-12600,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12600: OpenCV through 3.3 has a denial of service (CPU consumption) issue, as demonstrated by the 11-opencv-dos-cpu-exhaust test case."
91,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-12598,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12598: OpenCV through 3.3 has an out-of-bounds read error in the cv::RBaseStream::readBlock function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 8-opencv-invalid-read-fread test case."
92,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
93,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
94,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
95,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
96,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2019-19624,<4.1.0.25,"Opencv-python 4.1.0.25 includes a fix for CVE-2019-19624: An out-of-bounds read was discovered in OpenCV before 4.1.1. Specifically, variable coarsest_scale is assumed to be greater than or equal to finest_scale within the calc()/ocl_calc() functions in dis_flow.cpp. However, this is not true when dealing with small images, leading to an out-of-bounds read of the heap-allocated arrays Ux and Uy."
97,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2019-9423,<4.1.1.26,"Opencv-python 4.1.1.26 includes a fix for CVE-2019-9423: In opencv calls that use libpng, there is a possible out of bounds write due to a missing bounds check. This could lead to local escalation of privilege with no additional execution privileges required. User interaction is not required for exploitation."
98,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2019-15939,<4.1.1.26,Opencv-python 4.1.1.26 includes a fix for CVE-2019-15939: An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.
99,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2019-16249,<4.1.2.30,Opencv-python 4.1.2.30 includes a fix for  CVE-2019-16249: OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.
100,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
101,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
102,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
103,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
104,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
105,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
106,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
107,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
108,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
109,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
110,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
111,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
112,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
113,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
114,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
115,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
116,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
117,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
118,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
119,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/segmentation_using_paddlepaddle_model/python/requirements.txt,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
120,flask,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2019-1010083,<0.12.3,"Flask 0.12.3 includes a fix for CVE-2019-1010083: Unexpected memory usage. The impact is denial of service. The attack vector is crafted encoded JSON data. NOTE: this may overlap CVE-2018-1000656.
https://github.com/pallets/flask/pull/2695/commits/0e1e9a04aaf29ab78f721cfc79ac2a691f6e3929"
121,flask,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2018-1000656,<0.12.3,flask version Before 0.12.3 contains a CWE-20: Improper Input Validation vulnerability in flask that can result in Large amount of memory usage possibly leading to denial of service. This attack appear to be exploitable via Attacker provides JSON data in incorrect encoding. This vulnerability appears to have been fixed in 0.12.3.
122,flask,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,PVE-2021-25820,<0.6.1,flask 0.6.1 fixes a security problem that allowed clients to download arbitrary files  if the host server was a windows based operating system and the client  uses backslashes to escape the directory the files where exposed from.
123,flask,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2023-30861,"<2.2.5,>=2.3.0,<2.3.2","Flask is a lightweight WSGI web application framework. When all of the following conditions are met, a response containing data intended for one client may be cached and subsequently sent by the proxy to other clients. If the proxy also caches 'Set-Cookie' headers, it may send one client's 'session' cookie to other clients. The severity depends on the application's use of the session and the proxy's behavior regarding cookies. The risk depends on all these conditions being met.

1. The application must be hosted behind a caching proxy that does not strip cookies or ignore responses with cookies.
2. The application sets 'session.permanent = True'
3. The application does not access or modify the session at any point during a request.
4. 'SESSION_REFRESH_EACH_REQUEST' enabled (the default).
5. The application does not set a 'Cache-Control' header to indicate that a page is private or should not be cached.

This happens because vulnerable versions of Flask only set the 'Vary: Cookie' header when the session is accessed or modified, not when it is refreshed (re-sent to update the expiration) without being accessed or modified. This issue has been fixed in versions 2.3.2 and 2.2.5."
124,ovmsclient,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,no one,no one,no one
125,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2016-1517,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2016-1517: OpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks.
126,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-12602,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12602: OpenCV through 3.3 has a denial of service (memory consumption) issue, as demonstrated by the 10-opencv-dos-memory-exhaust test case."
127,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-12603,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12603: OpenCV through 3.3 has an invalid write in the cv::RLByteStream::getBytes function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 2-opencv-heapoverflow-fseek test case."
128,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-12597,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12597: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread.
129,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-12599,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12599: OpenCV through 3.3 has an out-of-bounds read error in the function icvCvt_BGRA2BGR_8u_C4C3R when reading an image file by using cv::imread.
130,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-12606,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12606: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow4 in utils.cpp when reading an image file by using cv::imread.
131,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-12601,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12601: OpenCV through 3.3 has a buffer overflow in the cv::BmpDecoder::readData function in modules/imgcodecs/src/grfmt_bmp.cpp when reading an image file by using cv::imread, as demonstrated by the 4-buf-overflow-readData-memcpy test case."
132,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-12604,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for  CVE-2017-12604: OpenCV through 3.3 has an out-of-bounds write error in the FillUniColor function in utils.cpp when reading an image file by using cv::imread.
133,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-12600,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12600: OpenCV through 3.3 has a denial of service (CPU consumption) issue, as demonstrated by the 11-opencv-dos-cpu-exhaust test case."
134,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-12598,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12598: OpenCV through 3.3 has an out-of-bounds read error in the cv::RBaseStream::readBlock function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 8-opencv-invalid-read-fread test case."
135,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
136,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
137,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
138,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
139,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2019-19624,<4.1.0.25,"Opencv-python 4.1.0.25 includes a fix for CVE-2019-19624: An out-of-bounds read was discovered in OpenCV before 4.1.1. Specifically, variable coarsest_scale is assumed to be greater than or equal to finest_scale within the calc()/ocl_calc() functions in dis_flow.cpp. However, this is not true when dealing with small images, leading to an out-of-bounds read of the heap-allocated arrays Ux and Uy."
140,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2019-9423,<4.1.1.26,"Opencv-python 4.1.1.26 includes a fix for CVE-2019-9423: In opencv calls that use libpng, there is a possible out of bounds write due to a missing bounds check. This could lead to local escalation of privilege with no additional execution privileges required. User interaction is not required for exploitation."
141,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2019-15939,<4.1.1.26,Opencv-python 4.1.1.26 includes a fix for CVE-2019-15939: An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.
142,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2019-16249,<4.1.2.30,Opencv-python 4.1.2.30 includes a fix for  CVE-2019-16249: OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.
143,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
144,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
145,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
146,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
147,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
148,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
149,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
150,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
151,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
152,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
153,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
154,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
155,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
156,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
157,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
158,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
159,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
160,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
161,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
162,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/real_time_stream_analysis/python/requirements.txt,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
163,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
164,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
165,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
166,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
167,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
168,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
169,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
170,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
171,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
172,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
173,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
174,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
175,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
176,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
177,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
178,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
179,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
180,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
181,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
182,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
183,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
184,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
185,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
186,opencv-python,>=4.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
187,tensorflow-serving-api,==2.11.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,no one,no one,no one
188,futures,==3.1.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/common/python/requirements.txt,False,no one,no one,no one
189,onnxruntime,==1.14.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/gptj_causal_lm/python/requirements.txt,False,no one,no one,no one
190,torch,==1.13.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/gptj_causal_lm/python/requirements.txt,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
191,numpy,==1.23,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/gptj_causal_lm/python/requirements.txt,False,no one,no one,no one
192,ovmsclient,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/gptj_causal_lm/python/requirements.txt,False,no one,no one,no one
193,accelerate,==0.17.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/gptj_causal_lm/python/requirements.txt,False,no one,no one,no one
194,transformers,==4.26.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/gptj_causal_lm/python/requirements.txt,False,no one,no one,no one
195,tensorflow-serving-api,==2.11.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/universal-sentence-encoder/requirements.txt,False,no one,no one,no one
196,ovmsclient,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/demos/using_onnx_model/python/requirements.txt,False,no one,no one,no one
197,psutil,==5.7.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,no one,no one,no one
198,boto3,==1.14.14,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,no one,no one,no one
199,cpplint,==1.4.5,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,no one,no one,no one
200,pytest,==5.3.5,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,no one,no one,no one
201,docker,==5.0.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,no one,no one,no one
202,bandit,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,CVE-2017-18342,<1.6.3,Bandit 1.6.3 updates its dependency 'pyyaml' to v5.3.1 to include security fixes.
203,bandit,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,CVE-2020-1747,<1.6.3,Bandit 1.6.3 updates its dependency 'pyyaml' to v5.3.1 to include security fixes.
204,retry,==0.9.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,no one,no one,no one
205,cppclean,>=0.13,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,no one,no one,no one
206,grpcio,==1.53.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,no one,no one,no one
207,paramiko,==2.11.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,CVE-2018-7750,"<1.17.6,>=2.0.0,<2.0.8,>=2.1.0,<2.1.5,>=2.2.0,<2.2.3,>=2.3.0,<2.3.2,==2.4.0,>=1.18.0,<1.18.5","transport.py in the SSH server implementation of Paramiko before 1.17.6, 1.18.x before 1.18.5, 2.0.x before 2.0.8, 2.1.x before 2.1.5, 2.2.x before 2.2.3, 2.3.x before 2.3.2, and 2.4.x before 2.4.1 does not properly check whether authentication is completed before processing other requests, as demonstrated by channel-open. A customized SSH client can simply skip the authentication step."
208,paramiko,==2.11.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,CVE-2022-24302,">=0,<2.9.3,>=2.10.0,<2.10.1","In Paramiko before 2.10.1, a race condition (between creation and chmod) in the write_private_key_file function could allow unauthorized information disclosure."
209,protobuf,">=3.18,<4.0.0",/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,CVE-2022-1941,"<3.18.3,>=3.19.0rc0,<3.19.5,>=3.20.0rc0,<3.20.2,>=4.0.0rc0,<4.21.6","A parsing vulnerability for the MessageSet type in the ProtocolBuffers versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 3.21.5 for protobuf-cpp, and versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 4.21.5 for protobuf-python can lead to out of memory failures. A specially crafted message with multiple key-value per elements creates parsing issues, and can lead to a Denial of Service against services receiving unsanitized input. We recommend upgrading to versions 3.18.3, 3.19.5, 3.20.2, 3.21.6 for protobuf-cpp and 3.18.3, 3.19.5, 3.20.2, 4.21.6 for protobuf-python. Versions for 3.16 and 3.17 are no longer updated."
210,tensorflow-serving-api,==2.11.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,no one,no one,no one
211,pytest-json,==0.4.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/tests/requirements.txt,False,no one,no one,no one
212,protobuf,==3.19.5,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/kserve-api/samples/requirements.txt,False,CVE-2022-1941,"<3.18.3,>=3.19.0rc0,<3.19.5,>=3.20.0rc0,<3.20.2,>=4.0.0rc0,<4.21.6","A parsing vulnerability for the MessageSet type in the ProtocolBuffers versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 3.21.5 for protobuf-cpp, and versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 4.21.5 for protobuf-python can lead to out of memory failures. A specially crafted message with multiple key-value per elements creates parsing issues, and can lead to a Denial of Service against services receiving unsanitized input. We recommend upgrading to versions 3.18.3, 3.19.5, 3.20.2, 3.21.6 for protobuf-cpp and 3.18.3, 3.19.5, 3.20.2, 4.21.6 for protobuf-python. Versions for 3.16 and 3.17 are no longer updated."
213,requests,==2.31.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/kserve-api/samples/requirements.txt,False,CVE-2015-2296,">=2.1,<=2.5.3",The resolve_redirects function in sessions.py in requests 2.1.0 through 2.5.3 allows remote attackers to conduct session fixation attacks via a cookie without a host value in a redirect.
214,requests,==2.31.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/kserve-api/samples/requirements.txt,False,CVE-2023-32681,">=2.3.0,<2.31.0","Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use 'rebuild_proxies' to reattach the 'Proxy-Authorization' header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the 'Proxy-Authorization' header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.

"
215,grpcio,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/kserve-api/samples/requirements.txt,False,CVE-2017-7860,<1.2.0,"Grpcio 1.2.0 includes a fix for CVE-2017-7860: Google gRPC before 2017-02-22 has an out-of-bounds write caused by a heap-based buffer overflow related to the parse_unix function in core/ext/client_channel/parse_address.c.
https://github.com/grpc/grpc/pull/9833/commits/bcd5f12e4bca2ed2c00cddb5ffd046aef6f4fb31"
216,grpcio,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/kserve-api/samples/requirements.txt,False,CVE-2017-7861,<1.2.0,"Grpcio 1.2.0 includes a fix for CVE-2017-7861: Google gRPC before 2017-02-22 has an out-of-bounds write related to the gpr_free function in core/lib/support/alloc.c.
https://github.com/grpc/grpc/pull/9833/commits/bcd5f12e4bca2ed2c00cddb5ffd046aef6f4fb31"
217,grpcio,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/kserve-api/samples/requirements.txt,False,CVE-2017-8359,<1.3.0,"Grpcio 1.3.0 includes a fix for CVE-2017-8359: Google gRPC before 2017-03-29 has an out-of-bounds write caused by a heap-based use-after-free related to the grpc_call_destroy function in core/lib/surface/call.c.
https://github.com/grpc/grpc/pull/10353/commits/aab6992c006be6fb80df73fd9f218365099c016d"
218,grpcio,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/kserve-api/samples/requirements.txt,False,CVE-2017-9431,<1.3.0,"Grpcio 1.3.0 includes a fix for CVE-2017-9431: Google gRPC before 2017-04-05 has an out-of-bounds write caused by a heap-based buffer overflow related to core/lib/iomgr/error.c.
https://github.com/grpc/grpc/pull/10492/commits/c6ec1155d026c91b1badb07ef1605bb747cff064"
219,tritonclient,==2.22.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/kserve-api/samples/requirements.txt,False,no one,no one,no one
220,tensorflow-serving-api,==2.11.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/tensorflow-serving-api/samples/requirements.txt,False,no one,no one,no one
221,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
222,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
223,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
224,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
225,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
226,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
227,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
228,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
229,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
230,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
231,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
232,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
233,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
234,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
235,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
236,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
237,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
238,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
239,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
240,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
241,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
242,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
243,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
244,opencv-python,==4.5.3.56,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
245,ovmsclient,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/samples/requirements.txt,False,no one,no one,no one
246,grpcio,>=1.47.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/lib/setup.py,False,no one,no one,no one
247,protobuf,>=3.19.4,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/lib/setup.py,False,CVE-2022-1941,"<3.18.3,>=3.19.0rc0,<3.19.5,>=3.20.0rc0,<3.20.2,>=4.0.0rc0,<4.21.6","A parsing vulnerability for the MessageSet type in the ProtocolBuffers versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 3.21.5 for protobuf-cpp, and versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 4.21.5 for protobuf-python can lead to out of memory failures. A specially crafted message with multiple key-value per elements creates parsing issues, and can lead to a Denial of Service against services receiving unsanitized input. We recommend upgrading to versions 3.18.3, 3.19.5, 3.20.2, 3.21.6 for protobuf-cpp and 3.18.3, 3.19.5, 3.20.2, 4.21.6 for protobuf-python. Versions for 3.16 and 3.17 are no longer updated."
248,numpy,>=1.16.6,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/lib/setup.py,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
249,numpy,>=1.16.6,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/lib/setup.py,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
250,numpy,>=1.16.6,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/lib/setup.py,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
251,numpy,>=1.16.6,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/lib/setup.py,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
252,requests,>=2.27.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/lib/setup.py,False,CVE-2015-2296,">=2.1,<=2.5.3",The resolve_redirects function in sessions.py in requests 2.1.0 through 2.5.3 allows remote attackers to conduct session fixation attacks via a cookie without a host value in a redirect.
253,requests,>=2.27.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/lib/setup.py,False,CVE-2023-32681,">=2.3.0,<2.31.0","Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use 'rebuild_proxies' to reattach the 'Proxy-Authorization' header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the 'Proxy-Authorization' header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.

"
254,pytest_mock,==3.6.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/lib/tests/requirements.txt,False,no one,no one,no one
255,pytest,==6.2.4,/home/daniele/git/NICHE_projects/Repo/Cloneables/model_server/client/python/ovmsclient/lib/tests/requirements.txt,False,no one,no one,no one
