,dep,version,filepath,bloated,cve,affected versions,advisory
0,torchvision,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,no one,no one,no one
1,cython,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,no one,no one,no one
2,ninja,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,no one,no one,no one
3,torch,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
4,tqdm,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2016-10075,<4.11.2,The tqdm._version module in tqdm versions before 4.11.2 allows local users to execute arbitrary code via a crafted repo with a malicious git log in the current working directory.
5,matplotlib,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,no one,no one,no one
6,yacs,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,no one,no one,no one
7,scikit-image,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,no one,no one,no one
8,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2016-1517,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2016-1517: OpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks.
9,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-12602,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12602: OpenCV through 3.3 has a denial of service (memory consumption) issue, as demonstrated by the 10-opencv-dos-memory-exhaust test case."
10,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-12603,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12603: OpenCV through 3.3 has an invalid write in the cv::RLByteStream::getBytes function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 2-opencv-heapoverflow-fseek test case."
11,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-12597,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12597: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread.
12,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-12599,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12599: OpenCV through 3.3 has an out-of-bounds read error in the function icvCvt_BGRA2BGR_8u_C4C3R when reading an image file by using cv::imread.
13,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-12606,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12606: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow4 in utils.cpp when reading an image file by using cv::imread.
14,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-12601,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12601: OpenCV through 3.3 has a buffer overflow in the cv::BmpDecoder::readData function in modules/imgcodecs/src/grfmt_bmp.cpp when reading an image file by using cv::imread, as demonstrated by the 4-buf-overflow-readData-memcpy test case."
15,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-12604,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for  CVE-2017-12604: OpenCV through 3.3 has an out-of-bounds write error in the FillUniColor function in utils.cpp when reading an image file by using cv::imread.
16,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-12600,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12600: OpenCV through 3.3 has a denial of service (CPU consumption) issue, as demonstrated by the 11-opencv-dos-cpu-exhaust test case."
17,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-12598,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12598: OpenCV through 3.3 has an out-of-bounds read error in the cv::RBaseStream::readBlock function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 8-opencv-invalid-read-fread test case."
18,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
19,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
20,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
21,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
22,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2019-19624,<4.1.0.25,"Opencv-python 4.1.0.25 includes a fix for CVE-2019-19624: An out-of-bounds read was discovered in OpenCV before 4.1.1. Specifically, variable coarsest_scale is assumed to be greater than or equal to finest_scale within the calc()/ocl_calc() functions in dis_flow.cpp. However, this is not true when dealing with small images, leading to an out-of-bounds read of the heap-allocated arrays Ux and Uy."
23,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2019-9423,<4.1.1.26,"Opencv-python 4.1.1.26 includes a fix for CVE-2019-9423: In opencv calls that use libpng, there is a possible out of bounds write due to a missing bounds check. This could lead to local escalation of privilege with no additional execution privileges required. User interaction is not required for exploitation."
24,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2019-15939,<4.1.1.26,Opencv-python 4.1.1.26 includes a fix for CVE-2019-15939: An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.
25,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2019-16249,<4.1.2.30,Opencv-python 4.1.2.30 includes a fix for  CVE-2019-16249: OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.
26,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
27,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
28,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
29,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
30,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
31,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
32,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
33,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
34,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
35,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
36,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
37,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
38,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
39,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
40,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
41,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
42,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
43,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
44,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
45,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/requirements.txt,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
46,torchvision,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,no one,no one,no one
47,ninja,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,True,no one,no one,no one
48,yacs,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,no one,no one,no one
49,cython,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,True,no one,no one,no one
50,matplotlib,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,no one,no one,no one
51,tqdm,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2016-10075,<4.11.2,The tqdm._version module in tqdm versions before 4.11.2 allows local users to execute arbitrary code via a crafted repo with a malicious git log in the current working directory.
52,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2016-1517,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2016-1517: OpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks.
53,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-12602,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12602: OpenCV through 3.3 has a denial of service (memory consumption) issue, as demonstrated by the 10-opencv-dos-memory-exhaust test case."
54,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-12603,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12603: OpenCV through 3.3 has an invalid write in the cv::RLByteStream::getBytes function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 2-opencv-heapoverflow-fseek test case."
55,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-12597,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12597: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread.
56,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-12599,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12599: OpenCV through 3.3 has an out-of-bounds read error in the function icvCvt_BGRA2BGR_8u_C4C3R when reading an image file by using cv::imread.
57,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-12606,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12606: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow4 in utils.cpp when reading an image file by using cv::imread.
58,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-12601,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12601: OpenCV through 3.3 has a buffer overflow in the cv::BmpDecoder::readData function in modules/imgcodecs/src/grfmt_bmp.cpp when reading an image file by using cv::imread, as demonstrated by the 4-buf-overflow-readData-memcpy test case."
59,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-12604,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for  CVE-2017-12604: OpenCV through 3.3 has an out-of-bounds write error in the FillUniColor function in utils.cpp when reading an image file by using cv::imread.
60,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-12600,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12600: OpenCV through 3.3 has a denial of service (CPU consumption) issue, as demonstrated by the 11-opencv-dos-cpu-exhaust test case."
61,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-12598,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12598: OpenCV through 3.3 has an out-of-bounds read error in the cv::RBaseStream::readBlock function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 8-opencv-invalid-read-fread test case."
62,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
63,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
64,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
65,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
66,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2019-19624,<4.1.0.25,"Opencv-python 4.1.0.25 includes a fix for CVE-2019-19624: An out-of-bounds read was discovered in OpenCV before 4.1.1. Specifically, variable coarsest_scale is assumed to be greater than or equal to finest_scale within the calc()/ocl_calc() functions in dis_flow.cpp. However, this is not true when dealing with small images, leading to an out-of-bounds read of the heap-allocated arrays Ux and Uy."
67,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2019-9423,<4.1.1.26,"Opencv-python 4.1.1.26 includes a fix for CVE-2019-9423: In opencv calls that use libpng, there is a possible out of bounds write due to a missing bounds check. This could lead to local escalation of privilege with no additional execution privileges required. User interaction is not required for exploitation."
68,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2019-15939,<4.1.1.26,Opencv-python 4.1.1.26 includes a fix for CVE-2019-15939: An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.
69,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2019-16249,<4.1.2.30,Opencv-python 4.1.2.30 includes a fix for  CVE-2019-16249: OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.
70,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
71,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
72,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
73,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
74,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
75,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
76,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
77,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
78,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
79,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
80,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
81,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
82,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
83,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
84,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
85,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
86,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
87,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
88,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
89,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
90,scikit-image,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/FCOS/setup.py,False,no one,no one,no one
