,dep,version,filepath,bloated,cve,affected versions,advisory
0,fastprogress,>=0.2.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements.txt,False,no one,no one,no one
1,pytensor,">=2.14.1,<2.15",/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements.txt,False,no one,no one,no one
2,scipy,>=1.4.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements.txt,False,CVE-2013-4251,">=0,<0.12.1",The scipy.weave component in SciPy before 0.12.1 creates insecure temporary directories.
3,cachetools,>=4.2.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements.txt,False,no one,no one,no one
4,typing-extensions,>=3.7.4,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements.txt,False,no one,no one,no one
5,numpy,>=1.15.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements.txt,False,CVE-2019-6446,<1.16.3,"Numpy 1.16.3 includes a fix for CVE-2019-6446: It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call.
https://github.com/numpy/numpy/commit/89b688732b37616c9d26623f81aaee1703c30ffb"
6,numpy,>=1.15.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements.txt,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
7,numpy,>=1.15.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements.txt,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
8,numpy,>=1.15.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements.txt,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
9,numpy,>=1.15.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements.txt,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
10,pandas,>=0.24.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements.txt,False,CVE-2020-13091,">=0,<1.0.4","** DISPUTED ** pandas through 1.0.3 can unserialize and execute commands from an untrusted file that is passed to the read_pickle() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the read_pickle() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner."
11,cloudpickle,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements.txt,False,no one,no one,no one
12,arviz,>=0.13.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements.txt,False,no one,no one,no one
13,mypy,==0.990,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
14,numpydoc,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
15,watermark,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
16,scipy,>=1.4.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2013-4251,">=0,<0.12.1",The scipy.weave component in SciPy before 0.12.1 creates insecure temporary directories.
17,sphinx,>=1.5,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2020-11023,<3.0.4,Sphinx 3.0.4 updates jQuery version from 3.4.1 to 3.5.1 for security reasons.
18,sphinx,>=1.5,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2020-11022,<3.0.4,Sphinx 3.0.4 updates jQuery version from 3.4.1 to 3.5.1 for security reasons.
19,typing-extensions,>=3.7.4,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
20,pytest,>=3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
21,mcbackend,>=0.4.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
22,cloudpickle,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
23,sphinx-copybutton,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
24,types-cachetools,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
25,arviz,>=0.13.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
26,sphinx-remove-toctrees,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
27,polyagamma,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
28,numpy,>=1.15.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2019-6446,<1.16.3,"Numpy 1.16.3 includes a fix for CVE-2019-6446: It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call.
https://github.com/numpy/numpy/commit/89b688732b37616c9d26623f81aaee1703c30ffb"
29,numpy,>=1.15.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
30,numpy,>=1.15.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
31,numpy,>=1.15.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
32,numpy,>=1.15.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
33,ipython,>=7.16,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2023-24816,<8.10.0,"IPython 8.10.0 includes a fix for CVE-2023-24816: Versions prior to 8.10.0 are subject to a command injection vulnerability with very specific prerequisites. This vulnerability requires that the function 'IPython.utils.terminal.set_term_title' be called on Windows in a Python environment where ctypes is not available. The dependency on 'ctypes' in 'IPython.utils._process_win32' prevents the vulnerable code from ever being reached in the ipython binary. However, as a library that could be used by another tool 'set_term_title' could be called and hence introduce a vulnerability. If an attacker get untrusted input to an instance of this function they would be able to inject shell commands as current process and limited to the scope of the current process. As a workaround, users should ensure that any calls to the 'IPython.utils.terminal.set_term_title' function are done with trusted or filtered input.
https://github.com/ipython/ipython/security/advisories/GHSA-29gw-9793-fvw7"
34,ipython,>=7.16,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2014-3429,">=0.12,<1.2","IPython Notebook 0.12 through 1.x before 1.2 does not validate the origin of websocket requests, which allows remote attackers to execute arbitrary code by leveraging knowledge of the kernel id and a crafted page."
35,ipython,>=7.16,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2016-6524,">=2.0.0,<4.0.0",Ipython 4.0 includes a fix for CVE-2016-6524: Untrusted LaTeX output could be added to the page in a way that could execute javascript.
36,ipython,>=7.16,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2015-4706,">=3.0.0,<3.2.0",Cross-site scripting (XSS) vulnerability in IPython 3.x before 3.2 allows remote attackers to inject arbitrary web script or HTML via vectors involving JSON error messages and the /api/contents path.
37,ipython,>=7.16,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2022-21699,">=8.0.0a0,<8.0.1,>=7.17.0,<7.31.1,>=6.0.0a0,<7.16.3,<5.11","Ipython versions 8.0.1, 7.31.1, 7.16.3 and 5.11 include a fix for CVE-2022-21699: Affected versions are subject to an arbitrary code execution vulnerability achieved by not properly managing cross user temporary files. This vulnerability allows one user to run code as another on the same machine.
https://github.com/ipython/ipython/security/advisories/GHSA-pq7m-3gw7-gq5x"
38,fastprogress,>=0.2.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
39,pymc-sphinx-theme,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
40,pytensor,">=2.14.1,<2.15",/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
41,sphinx-notfound-page,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
42,h5py,>=2.7,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
43,pandas,>=0.24.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,CVE-2020-13091,">=0,<1.0.4","** DISPUTED ** pandas through 1.0.3 can unserialize and execute commands from an untrusted file that is passed to the read_pickle() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the read_pickle() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner."
44,myst-nb,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
45,sphinxext-rediraffe,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
46,jupyter-sphinx,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
47,sphinx-design,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
48,cachetools,>=4.2.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
49,pytest-cov,>=2.5,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
50,numdifftools,>=0.9.40,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
51,pre-commit,>=2.8.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/requirements-dev.txt,False,no one,no one,no one
52,pytest,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/setup.py,False,no one,no one,no one
53,pytest-cov,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pymc3/setup.py,False,no one,no one,no one
