,dep,version,filepath,bloated,cve,affected versions,advisory
0,tqdm,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2016-10075,<4.11.2,The tqdm._version module in tqdm versions before 4.11.2 allows local users to execute arbitrary code via a crafted repo with a malicious git log in the current working directory.
1,box2d-py,==2.3.8,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,no one,no one,no one
2,pyzmq,==20.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,no one,no one,no one
3,addict,==2.4.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,no one,no one,no one
4,wandb,==0.10.11,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,PVE-2022-47988,<0.12.12,"Wandb 0.12.12 fixes an unsafe temporary file creation vulnerability.
https://github.com/wandb/client/pull/3360"
5,wandb,==0.10.11,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2021-33503,<0.12.18,Wandb 0.12.18 updates its dependency 'urllib3' to v1.26.5 to include security fixes.
6,wandb,==0.10.11,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2020-7212,<0.12.18,Wandb 0.12.18 updates its dependency 'urllib3' to v1.26.5 to include security fixes.
7,wandb,==0.10.11,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2020-11078,<0.12.18,Wandb 0.12.18 updates its dependency 'httplib2' to v0.19.0 to include security fixes.
8,wandb,==0.10.11,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2020-26137,<0.12.18,Wandb 0.12.18 updates its dependency 'urllib3' to v1.26.5 to include security fixes.
9,wandb,==0.10.11,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2020-13757,<0.12.18,Wandb 0.12.18 updates its dependency 'rsa' to v4.7 to include security fixes.
10,wandb,==0.10.11,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2020-25658,<0.12.18,Wandb 0.12.18 updates its dependency 'rsa' to v4.7 to include security fixes.
11,wandb,==0.10.11,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2021-21240,<0.12.18,Wandb 0.12.18 updates its dependency 'httplib2' to v0.19.0 to include security fixes.
12,redis,==3.5.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2023-28858,"<4.3.6,>=4.4.0rc1,<4.4.3,>=4.5.0rc1,<4.5.3","Redis before 4.5.3 leaves a connection open after canceling an async Redis command at an inopportune time, and can send response data to the client of an unrelated request in an off-by-one manner. NOTE: this CVE Record was initially created in response to reports about ChatGPT, and 4.3.6, 4.4.3, and 4.5.3 were released (changing the behavior for pipeline operations); however, please see CVE-2023-28859 about addressing data leakage across AsyncIO connections in general."
13,redis,==3.5.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2023-28859,"<4.4.4,>=4.5.0rc0,<4.5.4","Redis 4.4.4 and 4.5.4 include a fix for CVE-2023-28859: Redis-py before 4.4.4 and 4.5.x before 4.5.4 leaves a connection open after canceling an async Redis command at an inopportune time, and can send response data to the client of an unrelated request. (This could, for example, happen for a non-pipeline operation.) NOTE: the solutions for CVE-2023-28859 address data leakage across AsyncIO connections in general."
14,ray,==1.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2021-44832,<1.10.0,Ray 1.10.0 updates its dependency 'log4j' to v2.17.1 to include a security fix.
15,ray,==1.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,PVE-2021-42426,<1.8.0,"Ray 1.8.0 fixes a race condition for the stats_fn when using multi-gpu. That caused an issue for any algorithm in which the loss function stores values as members in the policy for later retrieval.
https://github.com/ray-project/ray/issues/18812"
16,ray,==1.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2021-45046,<1.9.1,"Ray 1.9.1 updates its dependency 'log4j' to v2.16.0 to include security fixes.
https://github.com/ray-project/ray/commit/2cdbf974ea63caf4323aacbccaef2394a14a8562"
17,ray,==1.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2021-44228,<1.9.1,"Ray 1.9.1 updates its dependency 'log4j' to v2.16.0 to include security fixes.
https://github.com/ray-project/ray/commit/2cdbf974ea63caf4323aacbccaef2394a14a8562"
18,ray,==1.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2021-45105,<1.9.2,Ray 1.9.2 updates its dependency 'log4j' to v2.17.0 to include a security fix.
19,six,>=1.13.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,no one,no one,no one
20,matplotlib,==3.3.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,no one,no one,no one
21,plotly,==4.13.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,no one,no one,no one
22,gym,==0.17.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,no one,no one,no one
23,pyarrow,==3.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2019-12410,">=0.12.0,<=0.14.1","While investigating UBSAN errors in https://github.com/apache/arrow/pull/5365 it was discovered Apache Arrow versions 0.12.0 to 0.14.1 left memory Array data uninitialized when reading RLE null data from parquet. This affected the C++, Python, Ruby and R implementations. The uninitialized memory could potentially be shared if are transmitted over the wire (for instance with Flight) or persisted in the streaming IPC and file formats."
24,pyarrow,==3.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2019-12408,">=0.14.0,<=0.14.1","It was discovered that the C++ implementation (which underlies the R, Python and Ruby implementations) of Apache Arrow 0.14.0 to 0.14.1 had a uninitialized memory bug when building arrays with null values in some cases. This can lead to uninitialized memory being unintentionally shared if Arrow Arrays are transmitted over the wire (for instance with Flight) or persisted in the streaming IPC and file formats."
25,scipy,==1.5.4,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2013-4251,">=0,<0.12.1",The scipy.weave component in SciPy before 0.12.1 creates insecure temporary directories.
26,atari-py,==0.2.6,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,no one,no one,no one
27,torch,==1.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
28,numpy,==1.18.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
29,numpy,==1.18.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
30,numpy,==1.18.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
31,numpy,==1.18.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
32,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
33,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
34,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
35,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
36,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
37,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
38,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
39,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
40,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
41,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
42,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
43,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
44,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
45,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
46,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
47,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
48,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
49,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
50,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
51,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
52,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
53,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
54,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
55,opencv-python,==4.4.0.46,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements.txt,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
56,pytest,==6.1.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,no one,no one,no one
57,flake8,==3.8.4,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,no one,no one,no one
58,pytest-cov,==2.10.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,no one,no one,no one
59,pytest-flake8,==1.0.6,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,no one,no one,no one
60,pytest-mypy,==0.4.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,no one,no one,no one
61,pylint,==2.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,PVE-2022-45185,<2.13.0,"Pylint 2.13.0 fixes a crash when using the doc_params extension.
https://github.com/PyCQA/pylint/issues/5322"
62,pylint,==2.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,PVE-2021-39621,<2.7.0,Pylint 2.7.0 includes a fix for vulnerable regular expressions in 'pyreverse'.
63,flake8-docstrings,==1.5.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,no one,no one,no one
64,pluggy,==0.13.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,no one,no one,no one
65,pytest-pylint,==0.18.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,no one,no one,no one
66,setuptools,==40.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,CVE-2022-40897,<65.5.1,"Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.
https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages"
67,black,==21.6b0,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,no one,no one,no one
68,flake8-bugbear,==20.11.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,no one,no one,no one
69,mypy,==0.761,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,no one,no one,no one
70,pre-commit,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,CVE-2017-18342,<1.10.4,"Pre-commit 1.10.4 replaces 'yaml.load' with safe alternative to avoid a remote code execution vulnerability.
https://github.com/pre-commit/pre-commit/commit/6853f4aa4c8d7e411839bacc66876baea443186a"
71,isort,==5.6.4,/home/daniele/git/NICHE_projects/Repo/Cloneables/rl_algorithms/requirements-dev.txt,False,no one,no one,no one
